//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Satış
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbladmin
    {
        public byte Id { get; set; }
        public string Şıfre { get; set; }
        public string KullanıcıAdı { get; set; }
    }
}
